// parity.test.js — v14
// Verifies our ES module port of the SwibSwap fee engine matches the handoff
// simulator exactly. The snapshot in parity_snapshot.json was generated by
// running the handoff zip's js/calc.js + NBT_Rate_3_2026-05-08.json through a
// Node vm context — that snapshot is the source of truth.
//
// Runs under CRA's Jest (`npm test`). If any case drifts, fix calc.js until
// every field in every case matches. NEVER edit the snapshot.

import { calc, calcChain } from '../calc.js';
import snapshot from './parity_snapshot.json';

const { nbt, single, chain } = snapshot;
const C        = nbt.constants;
const bsaRates = nbt.bsaRates;

// Tolerance for floating-point comparisons. Currency math operates at THB
// precision; 4 decimal places of equality covers all real-world cases.
const EPS = 1e-4;

function expectFieldsMatch(got, want, label) {
  for (const k of Object.keys(want)) {
    const wv = want[k];
    const gv = got[k];
    if (typeof wv === 'number' && wv !== null) {
      expect(Math.abs(gv - wv)).toBeLessThan(EPS);
    } else {
      expect(gv).toEqual(wv);
    }
  }
}

describe('Fee engine parity vs handoff simulator', () => {
  describe('Single-transaction calc()', () => {
    single.forEach(({ args, result }, idx) => {
      const [price, buyerTier, sellerTier, txType, deliveryMode, payment, sellerCost, feeOverride] = args;
      const label = `case ${idx + 1}: ฿${price} ${buyerTier}→${sellerTier} ${txType}/${deliveryMode}/${payment}`;
      test(label, () => {
        const got = calc(
          price, buyerTier, sellerTier, txType, deliveryMode, payment,
          sellerCost, feeOverride, C, bsaRates
        );
        expectFieldsMatch(got, result, label);
      });
    });
  });

  describe('Chain calc()', () => {
    chain.forEach(({ label, args, result }) => {
      test(label, () => {
        const got = calcChain(
          args.p0, args.buyerTier, args.sellerTier, args.txType, args.payment,
          args.chainHops, args.markup, args.feeOverride, C, bsaRates,
          args.subsequentPayback
        );

        // Compare transactions array node-by-node
        expect(got.transactions.length).toBe(result.transactions.length);
        got.transactions.forEach((tx, i) => {
          const want = result.transactions[i];
          expect(tx.step).toBe(want.step);
          expect(tx.seller).toBe(want.seller);
          expect(tx.buyer).toBe(want.buyer);
          expect(tx.isDelivery).toBe(want.isDelivery);
          expect(Math.abs(tx.price - want.price)).toBeLessThan(EPS);
          expect(Math.abs(tx.coinRefund - want.coinRefund)).toBeLessThan(EPS);
          expect(Math.abs(tx.consignRate - want.consignRate)).toBeLessThan(EPS);
          expectFieldsMatch(tx.tx, want.tx, `${label} tx[${i}]`);
        });

        // Compare nodes
        expect(got.nodes.length).toBe(result.nodes.length);
        got.nodes.forEach((node, i) => {
          const want = result.nodes[i];
          expect(node.label).toBe(want.label);
          expect(node.role).toBe(want.role);
          if (node.profit != null && want.profit != null) {
            expect(Math.abs(node.profit - want.profit)).toBeLessThan(EPS);
          }
          if (node.receives != null && want.receives != null) {
            expect(Math.abs(node.receives - want.receives)).toBeLessThan(EPS);
          }
        });
      });
    });
  });
});
